
CREATE TABLE ROLES(
	ID_ROLE SERIAL,
	NAME_ROLE CHAR(10),
	CONSTRAINT PK_ID_ROLE PRIMARY KEY (ID_ROLE)
);

CREATE TABLE USERS(
	RUT VARCHAR(10) NOT NULL,
	NAME_USER CHAR(15) NOT NULL,
	SURNAME CHAR(20) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASS VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20)NOT NULL,
	FK_USER_ROLE INT,
	CONSTRAINT PK_RUT PRIMARY KEY (RUT),
	FOREIGN KEY (FK_USER_ROLE) REFERENCES ROLES (ID_ROLE)
	
);

CREATE TABLE POSTS(
	ID_POST SERIAL,
	BODY VARCHAR NULL,
	IMAGE VARCHAR NULL,
	DATE_ALT DATE,
	DATE_MOD DATE,
	FK_USER VARCHAR(10),
	CONSTRAINT PK_ID_POST PRIMARY KEY (ID_POST),
	FOREIGN KEY (FK_USER) REFERENCES USERS (RUT)
);
